# https://github.com/circleci/frontend/blob/master/.circleci/config.yml

version: 2

jobs:
  build-packages:
    docker:
      - image: node:8.11

    working_directory: ~/app

    steps:
      - checkout
      - run: yarn
      - run: yarn build
      - run: yarn test
      - persist_to_workspace:
          root: .
          paths:
            - packages/*/dist

  publish-packages:
    docker:
      - image: node:8.11

    working_directory: ~/app

    steps:
      - checkout
      - run: yarn
      - attach_workspace:
          at: ~/app
      - run: |
          if git log -1 --pretty=%B | grep "^v[0-9]\+\.[0-9]\+\.[0-9]\+$"; then
            version=$(git log -1 --pretty=%B)
            yarn oao publish --no-confirm --no-changelog-updates --no-git-commit --new-version=$version
          fi


workflows:
  version: 2
  build:
    jobs:
      - build-packages
      - publish-packages:
          requires:
            - build-packages
          filters:
            tags:
              only: /^v.*/
