# https://github.com/circleci/frontend/blob/master/.circleci/config.yml

version: 2
jobs:
  build:
    docker:
      - image: node:8.11

    working_directory: ~/app

    steps:
      - checkout

      - run: "npm install --ignore-scripts"
      - run: "./node_modules/.bin/lerna exec -- npm install"
      - run: "./node_modules/.bin/lerna bootstrap"
      - run: "./node_modules/.bin/lerna exec -- npm run build"
      - run: "./node_modules/.bin/lerna exec -- npm run test"
      - run: "cd playground && ./node_modules/.bin/ts-node src/bootstrap.ts"