# https://github.com/circleci/frontend/blob/master/.circleci/config.yml

version: 2

jobs:
  build-packages:
    docker:
      - image: node:8.11

    working_directory: ~/app

    steps:
      - checkout
      - run: make clean-install
      - run: make build
    #   - persist_to_workspace:
    #       root: .
    #       paths:
    #         - packages/*/dist

#   publish-packages:
#     docker:
#       - image: node:8.11

#     working_directory: ~/app

#     steps:
#       - checkout
#       - run: make install
#       - attach_workspace:
#           at: ~/app
#       - run: |
#           if git describe | grep "^v[0-9]\+\.[0-9]\+\.[0-9]\+$"; then
#             version=$(git describe)
#             yarn oao publish --no-confirm --no-changelog --no-git-commit --new-version=$version
#           fi


workflows:
  version: 2
  build:
    jobs:
      - build-packages
    #   - publish-packages:
    #       requires:
    #         - build-packages
    #       filters:
    #         tags:
    #           only: /^v.*/
