#!/bin/sh

../node_modules/.bin/lerna publish
../node_modules/.bin/lerna-changelog --tag-from=v0.0.23 > CHANGELOG.md
git reset
git add CHANGELOG.md
git commit -m 'docs(changelog): update to latest version'
