site:
  title: Risio - Documentation
  url: https://risio.github.io/framework
  start_page: risio::index.adoc
content:
  sources:
  - url: ../
    tags: [0.0.44]
    start_path: docs
ui:
  bundle:
    url: ui/build/ui-bundle.zip
    snapshot: true
